export const SET_USERNAME = "SET_USERNAME";
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";

export const SET_SELECTED_TICKET = "SET_SELECTED_TICKET";
export const CLOSE_TICKET = "CLOSE_TICKET";
export const OPEN_TICKET = "OPEN_TICKET";
export const FAIL_TICKET = "FAIL_TICKET";
