export const SET_USERNAME = "SET_USERNAME";
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const CLEAR_DAY_EXPERIENCE = "CLEAR_DAY_EXPERIENCE";

export const SET_STAGE = "SET_STAGE";
export const NEXT_DAY = "NEXT_DAY";
export const SET_SELECTED_TICKET = "SET_SELECTED_TICKET";
export const CLOSE_TICKET = "CLOSE_TICKET";
export const OPEN_TICKET = "OPEN_TICKET";
export const FAIL_TICKET = "FAIL_TICKET";
export const FAIL_ALL_OPEN = "FAIL_ALL_OPEN";
export const DISASTER = "DISASTER";
export const RESET_TICKETS = "RESET_TICKETS";
